-- seeds/03_facts.sql
-- fact seeds

INSERT INTO facts (id, title, thumbnail, fact_date, category, fact_summary, fact_long_1, fact_long_2,image_url_1, image_url_2, parties_involved) VALUES (1,'Canadian Independence', 'https://www.buyflags.eu/sites/default/files/styles/medium/public/flags-image/state-flags/canada.png?itok=i7jzXf98', '07-01-2022', 'Diplomacy', 'The British North America Act received Royal Assent on 29th March 1867 and went into effect 1st July 1867. The Act united the three separate territories of Canada, Nova Scotia and New Brunswick into a single dominion called Canada.', 'Canada Act, also called Constitution Act of 1982, Canada’s constitution approved by the British Parliament on March 25, 1982, and proclaimed by Queen Elizabeth II on April 17, 1982, making Canada wholly independent. The document contains the original statute that established the Canadian Confederation in 1867 (the British North America Act), the amendments made to it by the British Parliament over the years, and new material resulting from negotiations between the federal and provincial governments between 1980 and 1982.', 'Queen Elizabeth II gave royal assent to the Canada Act on March 29, 115 years to the day after Queen Victoria, her great-great-grandmother, had approved the federation act of 1867. Thus the last legal tie with Great Britain was severed, and Canada became a fully sovereign state.', 'randomString for image url', 'randomString_2 for image url','United Kingdom, Queen Elizabeth, Canada');

INSERT INTO facts (id, title, thumbnail,fact_date, category, fact_summary, fact_long_1, fact_long_2, image_url_1,image_url_2, parties_involved) VALUES (2,'Invasion of Normandy','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYFu6BLAKb91XUVP3QZFGg6xkOqNEctB-YBH7Hx3iffIX8IXpkEZ2RyxdCBWmHnhC-Eos&usqp=CAU', '07-01-2022', 'War', 'Operation Overlord was the codename for the Battle of Normandy', 'Operation Overlord was the codename for the Battle of Normandy, the Allied operation that launched the successful invasion of German-occupied Western Europe during World War II. The operation was launched on 6 June 1944 with the Normandy Landings (D-Day). A 1,200-plane airborne assault preceded an amphibious assault involving more than 5,000 vessels. Nearly 160,000 troops crossed the English Channel on 6 June, and more than two million Allied troops were in France by the end of August.','The Allies failed to accomplish their objectives for the first day, but gained a tenuous foothold that they gradually expanded when they captured the port at Cherbourg on 26 June and the city of Caen on 21 July. A failed counterattack by German forces on 8 August left 50,000 soldiers of the German 7th Army trapped in the Falaise pocket. The Allies launched a second invasion from the Mediterranean Sea of southern France (code-named Operation Dragoon) on 15 August, and the Liberation of Paris followed on 25 August. German forces retreated east across the Seine on 30 August 1944, marking the close of Operation Overlord.','random_url_1', 'random_url_2','United States, United Kingdom, Canada, Poland'
);


INSERT INTO facts (id, title, thumbnail, fact_date, category, fact_summary, fact_long_1, fact_long_2, image_url_1, image_url_2, parties_involved) VALUES (3,'NOWHERE','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYFu6BLAKb91XUVP3QZFGg6xkOqNEctB-YBH7Hx3iffIX8IXpkEZ2RyxdCBWmHnhC-Eos&usqp=CAU','07-02-2022','SOMETHING','RANDOM SUMMARY', 'SOME RANDOM FACT', 'ANOTHER RANDOM FACT','IMAGE1','IMAGE2','RANDOM PARTIES');